"""FastAPI application factory + lifespan.

Boots the multimodal-ai-assistant backend on 127.0.0.1:9000 (per docs/SECURITY.md §2.2).

Endpoints mounted:
- GET /              → service banner
- GET /health        → liveness probe
- GET /docs          → OpenAPI UI (auto-generated by FastAPI)
- GET /openapi.json  → OpenAPI schema (auto-generated)
- /api/v1/*          → all real endpoints (auth, me, etc.) — added by feat-026+

Reference: docs/项目总执行计划.md §21 + §23, feat-016 in feature_list.json.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.app.api import health
from backend.app.core.config import get_settings


logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Log startup/shutdown banners. Real services (DB, vLLM, agent) attach later."""
    settings = get_settings()
    logger.info(
        "Starting multimodal-backend env=%s host=%s port=%d",
        settings.environment,
        settings.host,
        settings.port,
    )
    yield
    logger.info("Stopping multimodal-backend")


def create_app() -> FastAPI:
    """Application factory. Called by uvicorn: `uvicorn backend.app.main:app`."""
    settings = get_settings()

    app = FastAPI(
        title="Multimodal AI Assistant Backend",
        version="0.1.0",
        description=(
            "Auth + chat + media orchestration for the Qwen3-VL-powered assistant. "
            "See docs/项目总执行计划.md §21-§26 for the full roadmap."
        ),
        lifespan=lifespan,
        # OpenAPI tags auto-group endpoints; default /docs + /openapi.json are kept.
    )

    # CORS — V1 dev: allow all. Tighten in PROD when api.example.com lands (feat-022/023/024).
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"] if settings.environment != "production" else [settings.allowed_origins],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Banner + health (feat-016 core)
    app.include_router(health.router)

    # Future routers mounted here by feat-026+:
    # app.include_router(auth.router, prefix="/api/v1")
    # app.include_router(me.router, prefix="/api/v1")

    return app


app = create_app()